# ps_07

In [5]:
import numpy as np 
import scipy as sp 

## Challenge Problem

In [11]:
def v(n):
    arr = []
    for i in range(n):
        if i == 1 or i == n-1:
            arr.append(1)
            continue
        arr.append(0)
    return arr

for i in range(5,13):
    matrix = sp.linalg.toeplitz(v(i))
    print(f"matrix:\n{matrix}\ndet={sp.linalg.det(matrix)}")

matrix:
[[0 1 0 0 1]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [1 0 0 1 0]]
det=2.0
matrix:
[[0 1 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]
det=-4.0
matrix:
[[0 1 0 0 0 0 1]
 [1 0 1 0 0 0 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1]
 [1 0 0 0 0 1 0]]
det=2.0
matrix:
[[0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 1 0]]
det=0.0
matrix:
[[0 1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 1 0]]
det=2.0
matrix:
[[0 1 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 0 1 0]]
det=-4.0
matrix:
[[0 1 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 

In [16]:
def cofactor(m):
    return np.linalg.inv(m).T * np.linalg.det(m)

for i in range(5,13):
    try: # in case of singular matrices
        matrix = sp.linalg.toeplitz(v(i))
        print(f"matrix:\n{matrix}\ndet={sp.linalg.det(matrix)}\ncofactor=\n{cofactor(matrix)}")
    except:
        print(f"matrix:\n{matrix}\ndet={sp.linalg.det(matrix)}\ncofactor=singular")

matrix:
[[0 1 0 0 1]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [1 0 0 1 0]]
det=2.0
cofactor=
[[ 1.  1. -1. -1.  1.]
 [ 1.  1.  1. -1. -1.]
 [-1.  1.  1.  1. -1.]
 [-1. -1.  1.  1.  1.]
 [ 1. -1. -1.  1.  1.]]
matrix:
[[0 1 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]
det=-4.0
cofactor=
[[-0. -2. -0.  2. -0. -2.]
 [-2. -0. -2. -0.  2. -0.]
 [-0. -2. -0. -2. -0.  2.]
 [ 2. -0. -2. -0. -2. -0.]
 [-0.  2. -0. -2. -0. -2.]
 [-2. -0.  2. -0. -2. -0.]]
matrix:
[[0 1 0 0 0 0 1]
 [1 0 1 0 0 0 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1]
 [1 0 0 0 0 1 0]]
det=2.0
cofactor=
[[-1.  1.  1. -1. -1.  1.  1.]
 [ 1. -1.  1.  1. -1. -1.  1.]
 [ 1.  1. -1.  1.  1. -1. -1.]
 [-1.  1.  1. -1.  1.  1. -1.]
 [-1. -1.  1.  1. -1.  1.  1.]
 [ 1. -1. -1.  1.  1. -1.  1.]
 [ 1.  1. -1. -1.  1.  1. -1.]]
matrix:
[[0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 1]
 [1 0 