# ps_06.ipynb

In [136]:
import numpy as np, math, scipy as sp

# Section 4.4 Problem 35

In [137]:
A = np.eye(4) - np.diag([1, 1, 1], -1)

Q, R = np.linalg.qr(A)

for i in range(100): # surely 100 should be enough
    Qt = Q * math.sqrt(i+1)
    print(f"i={i+1}\nQ={Qt}")

i=1
Q=[[-0.70710678 -0.40824829 -0.28867513  0.5       ]
 [ 0.70710678 -0.40824829 -0.28867513  0.5       ]
 [-0.          0.81649658 -0.28867513  0.5       ]
 [-0.         -0.          0.8660254   0.5       ]]
i=2
Q=[[-1.         -0.57735027 -0.40824829  0.70710678]
 [ 1.         -0.57735027 -0.40824829  0.70710678]
 [-0.          1.15470054 -0.40824829  0.70710678]
 [-0.         -0.          1.22474487  0.70710678]]
i=3
Q=[[-1.22474487 -0.70710678 -0.5         0.8660254 ]
 [ 1.22474487 -0.70710678 -0.5         0.8660254 ]
 [-0.          1.41421356 -0.5         0.8660254 ]
 [-0.         -0.          1.5         0.8660254 ]]
i=4
Q=[[-1.41421356 -0.81649658 -0.57735027  1.        ]
 [ 1.41421356 -0.81649658 -0.57735027  1.        ]
 [-0.          1.63299316 -0.57735027  1.        ]
 [-0.         -0.          1.73205081  1.        ]]
i=5
Q=[[-1.58113883 -0.91287093 -0.64549722  1.11803399]
 [ 1.58113883 -0.91287093 -0.64549722  1.11803399]
 [-0.          1.82574186 -0.64549722  1.1180339

from brute force: sqrt(2), sqrt(6), sqrt(3), sqrt(4)=2

In [138]:
Q[:, 0] = Qt[:, 0] * math.sqrt(2)
Q[:, 1] = Qt[:, 1] * math.sqrt(6)
Q[:, 2] = Qt[:, 2] * math.sqrt(3)
Q[:, 3] = Qt[:, 3] * math.sqrt(4)
print(Q)

[[-10. -10.  -5.  10.]
 [ 10. -10.  -5.  10.]
 [ -0.  20.  -5.  10.]
 [ -0.  -0.  15.  10.]]


# Section 5.1 Problem 31

In [139]:
for i in range(10):
    H = sp.linalg.hilbert(i+1)
    print(np.linalg.det(H))

H = sp.linalg.hilbert(5)
P, L, U = sp.linalg.lu(H)

print(U.round(3))

1.0
0.08333333333333333
0.00046296296296296146
1.6534391534392996e-07
3.749295132515227e-12
5.367299886816827e-18
4.835802608198562e-25
2.7370501354463325e-33
9.720265326886715e-43
2.1644052646213843e-53
[[ 1.     0.5    0.333  0.25   0.2  ]
 [ 0.     0.083  0.089  0.083  0.076]
 [ 0.     0.    -0.006 -0.008 -0.01 ]
 [ 0.     0.     0.     0.001  0.001]
 [ 0.     0.     0.     0.    -0.   ]]


# Section 5.1 Problem 32

In [140]:
n = [50, 100, 200, 400]
m = 100

# rand
for i in n:
    sum = 0
    for x in range(m): 
        A = np.random.randn(i, i)
        sum += np.linalg.det(A)

    print(f"n={i}; avg det={sum/m}")


n=50; avg det=1.797625287385875e+31
n=100; avg det=1.2222060847588453e+77
n=200; avg det=-6.541498366066371e+186


/tmp/ipykernel_28318/3247735537.py:9: RuntimeWarning: invalid value encountered in scalar add
  sum += np.linalg.det(A)


n=400; avg det=nan


Note: The results themselves seem to be random, but generally fall under the same scale.
Also, randn(400) overflowed LOL!